# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
