# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20160914_0801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacuna',
            new_name='Medicina',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='vacuna',
            new_name='medicina',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha',
            field=models.DateField(),
        ),
    ]
